apiVersion: apps/v1
kind: Deployment
metadata:
  name: yosoyapp
  namespace: apps
  labels:
    app: yosoyapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: yosoyapp
  template:
    metadata:
      labels:
        app: yosoyapp
    spec:
      containers:
        - name: yosoyapp
          image: us-central1-docker.pkg.dev/authentic-prod-464216/authenticfarma-microservices-test/yo-soy:v4
          env:
            - name: APP_NAME
              value: "Laravel"
            - name: APP_ENV
              value: "production"
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: yosoy-secrets
                  key: APP_KEY
            - name: APP_URL
              value: "https://app.yo-soy.co"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "127.0.0.1"  # Usar localhost para conectar al proxy
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "yosoy"
            - name: DB_USERNAME
              value: "userTest"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yosoy-secrets
                  key: DB_PASSWORD
            - name: LOG_CHANNEL
              value: "stack"
            - name: LOG_LEVEL
              value: "debug"
            - name: APP_DEBUG
              value: "false"
            - name: API_FLAG
              value: "true"
            - name: WEB_FLAG
              value: "true"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: yosoy-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: yosoy-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: "us-east-2"
            - name: AWS_BUCKET
              value: "yosoygaleria"
            - name: AWS_USE_PATH_STYLE_ENDPOINT
              value: "false"
            - name: MAIL_MAILER
              value: "smtp"
            - name: MAIL_HOST
              value: "smtp.gmail.com"
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_USERNAME
              value: "salud.femenina@yo-soy.co"
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yosoy-secrets
                  key: MAIL_PASSWORD
            - name: MAIL_ENCRYPTION
              value: "tls"
            - name: MAIL_FROM_ADDRESS
              value: "salud.femenina@yo-soy.co"
            - name: MAIL_FROM_NAME
              value: "Yo Soy"
            - name: RECAPTCHA_SITE_KEY
              value: "6Ld1fAsqAAAAANzajC8Iu96pX4SAQl2TKB3G53Zn"
            - name: RECAPTCHA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: yosoy-secrets
                  key: RECAPTCHA_SECRET_KEY
            - name: PASSPORT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: yosoy-secrets
                  key: PASSPORT_PRIVATE_KEY
            - name: PASSPORT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: yosoy-secrets
                  key: PASSPORT_PUBLIC_KEY
          ports:
            - name: web
              containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 300
            periodSeconds: 30
          # lifecycle:
          #   postStart:
          #     exec:
          #       command: ["/bin/sh", "-c", "php artisan passport:install"]
        
        # Cloud SQL Proxy sidecar
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
          command:
            - "/cloud_sql_proxy"
            - "-instances=authentic-prod-464216:us-central1:multiplataforma=tcp:3306"
            - "-credential_file=/secrets/cloudsql/credentials.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials